AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestrutura com S3 para site estático

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${SiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
    Description: URL do site